site_name: Climbing Notes
repo_url: https://github.com/Colin-TUE/climbing-notes
docs_dir: docs
use_directory_urls: false
site_author: Colin Lambrechts
site_description: A collection of climbing notes, make publicly available so others might benefit from them.
copyright: Copyright Colin Lambrechts - Licensed under MIT License for the non-attributed parts. Other parts may be under different licenses, see the individual files for details.

theme:
  name: material
  palette:
    scheme: iceberg
    primary: teal
    accent: deep_orange
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.indexes

nav:
  - Home: index.md
  - Norway:
      - Troldhuagen:
          - Just For Fun: Norway/JustForFun.md
