site_name: Climbing Notes
repository_url: https://github.com/Colin-TUE/climbing-notes
docs_dir: docs
use_directory_urls: false

theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.indexes

nav:
  - Home: index.md
  - Norway:
      - Troldhuagen:
          - Just For Fun: norway/JustForFun.md
