site_name: Climbing Notes
repo_url: https://github.com/Colin-TUE/climbing-notes
docs_dir: docs
use_directory_urls: false
site_author:
  name: Colin Lambrechts
  email: developer@koolin.eu
site_description: A collection of climbing notes, make publicly available so others might benefit from them.
copyright: Copyright Colin Lambrechts - Licenced under MIT License

theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.indexes

nav:
  - Home: index.md
  - Norway:
      - Troldhuagen:
          - Just For Fun: norway/JustForFun.md
