name: Main workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write

jobs:
  build-mkdocs-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build MkDocs pages
        uses: ./.github/actions/build-mkdocs-pages

  deploy-mkdocs-pages:
    runs-on: ubuntu-latest
    needs: build-mkdocs-pages
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    steps:
      - name: Deploy MkDocs pages
        uses: actions/deploy-pages@v4
