name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build-mkdocs-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build MkDocs pages
        uses: ./.github/actions/build-mkdocs-pages